#!/bin/sh
# Copyright (c) 2026 mumuxiao722
# SPDX-License-Identifier: MIT
set -e

udevadm control --reload-rules 2>/dev/null || true
systemctl daemon-reload 2>/dev/null || true
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    systemctl stop fake-tablet-mode.service >/dev/null 2>&1 || true
fi

exit 0