#!/bin/sh
# Copyright (c) 2026 mumuxiao722
# SPDX-License-Identifier: MIT
set -e

if [ "$1" = "remove" ] || [ "$1" = "upgrade" ]; then
    systemctl disable fake-tablet-mode.service >/dev/null 2>&1 || true
fi

exit 0